namespace SistemaConvenios.Data;

internal static class CatalogoSeedData
{
    public static readonly object[] AreasPromotoras =
    [
        new { Id = 1, Codigo = "VIN-001", Nombre = "Vinculación con la sociedad", Tipo = "Área interna", AreaPadreId = (int?)1015, Activo = true },
        new { Id = 2, Codigo = "PRA-001", Nombre = "Prácticas preprofesionales", Tipo = "Área interna", AreaPadreId = (int?)1015, Activo = true },
        new { Id = 3, Codigo = "INV-001", Nombre = "Investigación", Tipo = "Área interna", AreaPadreId = (int?)1015, Activo = true },
        new { Id = 4, Codigo = "ACA-001", Nombre = "Académica", Tipo = "Área interna", AreaPadreId = (int?)1015, Activo = true },
        new { Id = 1000, Codigo = "ULEAM", Nombre = "Universidad Laica Eloy Alfaro de Manabí", Tipo = "Institución", AreaPadreId = (int?)null, Activo = false },
        new { Id = 1001, Codigo = "ULEAM-001", Nombre = "AREAS DE LA SALUD", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1002, Codigo = "ULEAM-002", Nombre = "ARQUITECTURA", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1003, Codigo = "ULEAM-003", Nombre = "ARTES, HUMANIDADES Y PATRIMONIO", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1004, Codigo = "ULEAM-004", Nombre = "BAHÍA DE CARÁQUEZ", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1005, Codigo = "ULEAM-005", Nombre = "CAMPUS FLAVIO ALFARO", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1006, Codigo = "ULEAM-006", Nombre = "CAMPUS JUNÍN", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1007, Codigo = "ULEAM-007", Nombre = "CAMPUS PICHINCHA", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1008, Codigo = "ULEAM-008", Nombre = "CHONE", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1009, Codigo = "ULEAM-009", Nombre = "CIENCIAS ADMINISTRATIVAS", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1010, Codigo = "ULEAM-010", Nombre = "CIENCIAS ADMINISTRATIVAS, CONTABLES Y COMERCIO", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1011, Codigo = "ULEAM-011", Nombre = "CIENCIAS AGROPECUARIAS", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1012, Codigo = "ULEAM-012", Nombre = "CIENCIAS DE LA COMUNICACIÓN", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1013, Codigo = "ULEAM-013", Nombre = "CIENCIAS DE LA EDUCACIÓN", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1014, Codigo = "ULEAM-014", Nombre = "CIENCIAS DE LA SALUD", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1015, Codigo = "ULEAM-015", Nombre = "CIENCIAS DE LA VIDA Y TECNOLOGÍAS", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1016, Codigo = "ULEAM-016", Nombre = "CIENCIAS DEL MAR", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1017, Codigo = "ULEAM-017", Nombre = "CIENCIAS ECONÓMICAS", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1018, Codigo = "ULEAM-018", Nombre = "CIENCIAS INFORMÁTICAS", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1019, Codigo = "ULEAM-019", Nombre = "CIENCIAS MÉDICAS", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1020, Codigo = "ULEAM-020", Nombre = "CIENCIAS SOCIALES, DERECHO Y BIENESTAR", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1021, Codigo = "ULEAM-021", Nombre = "COMERCIO EXTERIOR Y NEGOCIOS INTERNACIONALES", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1022, Codigo = "ULEAM-022", Nombre = "CONTABILIDAD Y AUDITORÍA", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1023, Codigo = "ULEAM-023", Nombre = "DERECHO", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1024, Codigo = "ULEAM-024", Nombre = "EDUCACIÓN FÍSICA DEPORTES Y RECREACIÓN", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1025, Codigo = "ULEAM-025", Nombre = "EDUCACIÓN Y TURISMO", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1026, Codigo = "ULEAM-026", Nombre = "EL CARMEN", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1027, Codigo = "ULEAM-027", Nombre = "GESTIÓN ORGANIZACIONAL", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1028, Codigo = "ULEAM-028", Nombre = "HOTELERÍA Y TURISMO", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1029, Codigo = "ULEAM-029", Nombre = "INGENIERÍA", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1030, Codigo = "ULEAM-030", Nombre = "INGENIERÍA INDUSTRIAL", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1031, Codigo = "ULEAM-031", Nombre = "INGENIERÍA, INDUSTRIA, Y ARQUITECTURA", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1032, Codigo = "ULEAM-032", Nombre = "INSTITUTO DE IDIOMAS", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1033, Codigo = "ULEAM-033", Nombre = "MECÁNICA NAVAL", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1034, Codigo = "ULEAM-034", Nombre = "ODONTOLOGÍA", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1035, Codigo = "ULEAM-035", Nombre = "PEDERNALES", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1036, Codigo = "ULEAM-036", Nombre = "PSICOLOGÍA", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1037, Codigo = "ULEAM-037", Nombre = "SEDE SANTO DOMINGO DE LOS TSÁCHILAS", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1038, Codigo = "ULEAM-038", Nombre = "TRABAJO SOCIAL", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
        new { Id = 1039, Codigo = "ULEAM-039", Nombre = "UNIDAD ACADÉMICA DE FORMACIÓN TÉCNICA Y TECNOLÓGICA, EDUCACIÓN VIRTUAL Y OTRAS MODALIDADES DE ESTUDIO", Tipo = "Unidad académica", AreaPadreId = (int?)1000, Activo = true },
    ];

    public static readonly object[] Facultades =
    [
        new { Id = 1, Nombre = "Facultad de Ciencias de la Vida y Tecnologías", Siglas = "FCVT", Activo = false },
        new { Id = 1001, Nombre = "AREAS DE LA SALUD", Siglas = "AS", Activo = true },
        new { Id = 1002, Nombre = "ARQUITECTURA", Siglas = "A", Activo = true },
        new { Id = 1003, Nombre = "ARTES, HUMANIDADES Y PATRIMONIO", Siglas = "AHP", Activo = true },
        new { Id = 1004, Nombre = "BAHÍA DE CARÁQUEZ", Siglas = "BC", Activo = true },
        new { Id = 1005, Nombre = "CAMPUS FLAVIO ALFARO", Siglas = "CFA", Activo = true },
        new { Id = 1006, Nombre = "CAMPUS JUNÍN", Siglas = "CJ", Activo = true },
        new { Id = 1007, Nombre = "CAMPUS PICHINCHA", Siglas = "CP", Activo = true },
        new { Id = 1008, Nombre = "CHONE", Siglas = "C", Activo = true },
        new { Id = 1009, Nombre = "CIENCIAS ADMINISTRATIVAS", Siglas = "CA", Activo = true },
        new { Id = 1010, Nombre = "CIENCIAS ADMINISTRATIVAS, CONTABLES Y COMERCIO", Siglas = "CACC", Activo = true },
        new { Id = 1011, Nombre = "CIENCIAS AGROPECUARIAS", Siglas = "CA", Activo = true },
        new { Id = 1012, Nombre = "CIENCIAS DE LA COMUNICACIÓN", Siglas = "CC", Activo = true },
        new { Id = 1013, Nombre = "CIENCIAS DE LA EDUCACIÓN", Siglas = "CE", Activo = true },
        new { Id = 1014, Nombre = "CIENCIAS DE LA SALUD", Siglas = "CS", Activo = true },
        new { Id = 1015, Nombre = "CIENCIAS DE LA VIDA Y TECNOLOGÍAS", Siglas = "CVT", Activo = true },
        new { Id = 1016, Nombre = "CIENCIAS DEL MAR", Siglas = "CM", Activo = true },
        new { Id = 1017, Nombre = "CIENCIAS ECONÓMICAS", Siglas = "CE", Activo = true },
        new { Id = 1018, Nombre = "CIENCIAS INFORMÁTICAS", Siglas = "CI", Activo = true },
        new { Id = 1019, Nombre = "CIENCIAS MÉDICAS", Siglas = "CM", Activo = true },
        new { Id = 1020, Nombre = "CIENCIAS SOCIALES, DERECHO Y BIENESTAR", Siglas = "CSDB", Activo = true },
        new { Id = 1021, Nombre = "COMERCIO EXTERIOR Y NEGOCIOS INTERNACIONALES", Siglas = "CENI", Activo = true },
        new { Id = 1022, Nombre = "CONTABILIDAD Y AUDITORÍA", Siglas = "CA", Activo = true },
        new { Id = 1023, Nombre = "DERECHO", Siglas = "D", Activo = true },
        new { Id = 1024, Nombre = "EDUCACIÓN FÍSICA DEPORTES Y RECREACIÓN", Siglas = "EFDR", Activo = true },
        new { Id = 1025, Nombre = "EDUCACIÓN Y TURISMO", Siglas = "ET", Activo = true },
        new { Id = 1026, Nombre = "EL CARMEN", Siglas = "C", Activo = true },
        new { Id = 1027, Nombre = "GESTIÓN ORGANIZACIONAL", Siglas = "GO", Activo = true },
        new { Id = 1028, Nombre = "HOTELERÍA Y TURISMO", Siglas = "HT", Activo = true },
        new { Id = 1029, Nombre = "INGENIERÍA", Siglas = "I", Activo = true },
        new { Id = 1030, Nombre = "INGENIERÍA INDUSTRIAL", Siglas = "II", Activo = true },
        new { Id = 1031, Nombre = "INGENIERÍA, INDUSTRIA, Y ARQUITECTURA", Siglas = "IIA", Activo = true },
        new { Id = 1032, Nombre = "INSTITUTO DE IDIOMAS", Siglas = "II", Activo = true },
        new { Id = 1033, Nombre = "MECÁNICA NAVAL", Siglas = "MN", Activo = true },
        new { Id = 1034, Nombre = "ODONTOLOGÍA", Siglas = "O", Activo = true },
        new { Id = 1035, Nombre = "PEDERNALES", Siglas = "P", Activo = true },
        new { Id = 1036, Nombre = "PSICOLOGÍA", Siglas = "P", Activo = true },
        new { Id = 1037, Nombre = "SEDE SANTO DOMINGO DE LOS TSÁCHILAS", Siglas = "SSDT", Activo = true },
        new { Id = 1038, Nombre = "TRABAJO SOCIAL", Siglas = "TS", Activo = true },
        new { Id = 1039, Nombre = "UNIDAD ACADÉMICA DE FORMACIÓN TÉCNICA Y TECNOLÓGICA, EDUCACIÓN VIRTUAL Y OTRAS MODALIDADES DE ESTUDIO", Siglas = "UAFTTEVOME", Activo = true },
    ];

    public static readonly object[] Carreras =
    [
        new { Id = 1, Nombre = "Ingeniería de Software", Siglas = "IS", FacultadId = 1, Activo = false },
        new { Id = 2, Nombre = "Ingeniería Ambiental", Siglas = "IA", FacultadId = 1, Activo = false },
        new { Id = 3, Nombre = "Medicina Veterinaria", Siglas = "MV", FacultadId = 1, Activo = false },
        new { Id = 100001, Nombre = "NUTRICION Y DIETETICA", Siglas = "ND", FacultadId = 1001, Activo = true },
        new { Id = 100002, Nombre = "TERAPIA OCUPACIONAL", Siglas = "TO", FacultadId = 1001, Activo = true },
        new { Id = 100003, Nombre = "TERAPIA DEL LENGUAJE", Siglas = "TL", FacultadId = 1001, Activo = true },
        new { Id = 100004, Nombre = "RADIOLOGIA E IMAGENOLOGIA", Siglas = "RI", FacultadId = 1001, Activo = true },
        new { Id = 100005, Nombre = "FISIOTERAPIA", Siglas = "F", FacultadId = 1001, Activo = true },
        new { Id = 100006, Nombre = "LABORATORIO CLINICO", Siglas = "LC", FacultadId = 1001, Activo = true },
        new { Id = 100007, Nombre = "ARQUITECTURA", Siglas = "A", FacultadId = 1002, Activo = true },
        new { Id = 100008, Nombre = "ARTES PLÁSTICAS", Siglas = "AP", FacultadId = 1003, Activo = true },
        new { Id = 100009, Nombre = "ARTES ESCÉNICAS", Siglas = "AE", FacultadId = 1003, Activo = true },
        new { Id = 100010, Nombre = "DISEÑO TEXTIL E INDUMENTARIA", Siglas = "DTI", FacultadId = 1003, Activo = true },
        new { Id = 100011, Nombre = "ARQUEOLOGIA", Siglas = "A", FacultadId = 1003, Activo = true },
        new { Id = 100012, Nombre = "SOCIOLOGIA", Siglas = "S", FacultadId = 1003, Activo = true },
        new { Id = 100013, Nombre = "ARQUEOLOGIA", Siglas = "A", FacultadId = 1004, Activo = true },
        new { Id = 100014, Nombre = "GESTIÓN DEL TALENTO HUMANO", Siglas = "GTH", FacultadId = 1004, Activo = true },
        new { Id = 100015, Nombre = "HOSPITALIDAD Y HOTELERIA", Siglas = "HH", FacultadId = 1004, Activo = true },
        new { Id = 100016, Nombre = "CONTABILIDAD Y AUDITORIA", Siglas = "CA", FacultadId = 1004, Activo = true },
        new { Id = 100017, Nombre = "DERECHO", Siglas = "D", FacultadId = 1004, Activo = true },
        new { Id = 100018, Nombre = "TURISMO", Siglas = "T", FacultadId = 1004, Activo = true },
        new { Id = 100019, Nombre = "CIENCIAS DE LA COMUNICACION MENCION PUBLICIDAD Y MERCADOTECNIA", Siglas = "CCMPM", FacultadId = 1004, Activo = true },
        new { Id = 100020, Nombre = "FISIOTERAPIA", Siglas = "F", FacultadId = 1004, Activo = true },
        new { Id = 100021, Nombre = "EDUCACION INICIAL", Siglas = "EI", FacultadId = 1004, Activo = true },
        new { Id = 100022, Nombre = "ADMINISTRACIÓN DE EMPRESAS", Siglas = "AE", FacultadId = 1004, Activo = true },
        new { Id = 100023, Nombre = "EDUCACION BASICA", Siglas = "EB", FacultadId = 1004, Activo = true },
        new { Id = 100024, Nombre = "ENFERMERÍA", Siglas = "E", FacultadId = 1004, Activo = true },
        new { Id = 100025, Nombre = "GASTRONOMIA", Siglas = "G", FacultadId = 1004, Activo = true },
        new { Id = 100026, Nombre = "MERCADOTECNIA", Siglas = "M", FacultadId = 1004, Activo = true },
        new { Id = 100027, Nombre = "CONSTRUCCION SISMORRESISTENTE", Siglas = "CS", FacultadId = 1004, Activo = true },
        new { Id = 100028, Nombre = "AGRONEGOCIOS", Siglas = "A", FacultadId = 1004, Activo = true },
        new { Id = 100029, Nombre = "TURISMO SOSTENIBLE", Siglas = "TS", FacultadId = 1004, Activo = true },
        new { Id = 100030, Nombre = "EDUCACION INICIAL", Siglas = "EI", FacultadId = 1005, Activo = true },
        new { Id = 100031, Nombre = "SOFTWARE", Siglas = "S", FacultadId = 1005, Activo = true },
        new { Id = 100032, Nombre = "EDUCACION BASICA", Siglas = "EB", FacultadId = 1006, Activo = true },
        new { Id = 100033, Nombre = "AGRONEGOCIOS", Siglas = "A", FacultadId = 1007, Activo = true },
        new { Id = 100034, Nombre = "EDUCACION BASICA", Siglas = "EB", FacultadId = 1007, Activo = true },
        new { Id = 100035, Nombre = "ELECTRICIDAD", Siglas = "E", FacultadId = 1008, Activo = true },
        new { Id = 100036, Nombre = "ARTES PLÁSTICAS", Siglas = "AP", FacultadId = 1008, Activo = true },
        new { Id = 100037, Nombre = "PEDAGOGÍA DE LAS CIENCIAS EXPERIMENTALES", Siglas = "PCE", FacultadId = 1008, Activo = true },
        new { Id = 100038, Nombre = "ADMINISTRACIÓN DE EMPRESAS", Siglas = "AE", FacultadId = 1008, Activo = true },
        new { Id = 100039, Nombre = "ODONTOLOGIA", Siglas = "O", FacultadId = 1008, Activo = true },
        new { Id = 100040, Nombre = "TECNOLOGÍAS DE LA INFORMACIÓN", Siglas = "TI", FacultadId = 1008, Activo = true },
        new { Id = 100041, Nombre = "DERECHO", Siglas = "D", FacultadId = 1008, Activo = true },
        new { Id = 100042, Nombre = "ARQUITECTURA", Siglas = "A", FacultadId = 1008, Activo = true },
        new { Id = 100043, Nombre = "INGENIERÍA CIVIL", Siglas = "IC", FacultadId = 1008, Activo = true },
        new { Id = 100044, Nombre = "EDUCACION BASICA BILINGÜE", Siglas = "EBB", FacultadId = 1008, Activo = true },
        new { Id = 100045, Nombre = "MEDICINA", Siglas = "M", FacultadId = 1008, Activo = true },
        new { Id = 100046, Nombre = "PSICOLOGÍA EDUCATIVA", Siglas = "PE", FacultadId = 1008, Activo = true },
        new { Id = 100047, Nombre = "ALIMENTOS", Siglas = "A", FacultadId = 1008, Activo = true },
        new { Id = 100048, Nombre = "SOFTWARE", Siglas = "S", FacultadId = 1008, Activo = true },
        new { Id = 100049, Nombre = "NUTRICION Y DIETETICA", Siglas = "ND", FacultadId = 1008, Activo = true },
        new { Id = 100050, Nombre = "EDUCACION BASICA", Siglas = "EB", FacultadId = 1008, Activo = true },
        new { Id = 100051, Nombre = "EDUCACION INICIAL", Siglas = "EI", FacultadId = 1008, Activo = true },
        new { Id = 100052, Nombre = "PEDAGOGÍA DE LOS IDIOMAS NACIONALES Y EXTRANJEROS", Siglas = "PINE", FacultadId = 1008, Activo = true },
        new { Id = 100053, Nombre = "AGRONEGOCIOS", Siglas = "A", FacultadId = 1008, Activo = true },
        new { Id = 100054, Nombre = "INGENIERIA ELECTRICA", Siglas = "IE", FacultadId = 1008, Activo = true },
        new { Id = 100055, Nombre = "INGENIERIA CIVIL", Siglas = "IC", FacultadId = 1008, Activo = true },
        new { Id = 100056, Nombre = "ENFERMERÍA", Siglas = "E", FacultadId = 1008, Activo = true },
        new { Id = 100057, Nombre = "CONTABILIDAD Y AUDITORIA", Siglas = "CA", FacultadId = 1008, Activo = true },
        new { Id = 100058, Nombre = "FISIOTERAPIA", Siglas = "F", FacultadId = 1008, Activo = true },
        new { Id = 100059, Nombre = "ENTRENAMIENTO DEPORTIVO", Siglas = "ED", FacultadId = 1008, Activo = true },
        new { Id = 100060, Nombre = "AGROPECUARIA", Siglas = "A", FacultadId = 1008, Activo = true },
        new { Id = 100061, Nombre = "INGENIERIA AGROPECUARIA", Siglas = "IA", FacultadId = 1008, Activo = true },
        new { Id = 100062, Nombre = "INGENIERIA EN SISTEMAS", Siglas = "IS", FacultadId = 1008, Activo = true },
        new { Id = 100063, Nombre = "EDUCACIÓN INICIAL BILINGÜE", Siglas = "EIB", FacultadId = 1008, Activo = true },
        new { Id = 100064, Nombre = "INGENIERIA EN MARKETING", Siglas = "IM", FacultadId = 1009, Activo = true },
        new { Id = 100065, Nombre = "ADMINISTRACION DE EMPRESAS", Siglas = "AE", FacultadId = 1009, Activo = true },
        new { Id = 100066, Nombre = "GESTIÓN DE LA INFORMACIÓN GERENCIAL", Siglas = "GIG", FacultadId = 1010, Activo = true },
        new { Id = 100067, Nombre = "FINANZAS", Siglas = "F", FacultadId = 1010, Activo = true },
        new { Id = 100068, Nombre = "CONTABILIDAD Y AUDITORIA", Siglas = "CA", FacultadId = 1010, Activo = true },
        new { Id = 100069, Nombre = "COMERCIO EXTERIOR", Siglas = "CE", FacultadId = 1010, Activo = true },
        new { Id = 100070, Nombre = "SERVICIOS GERENCIALES", Siglas = "SG", FacultadId = 1010, Activo = true },
        new { Id = 100071, Nombre = "ADMINISTRACIÓN DE EMPRESAS", Siglas = "AE", FacultadId = 1010, Activo = true },
        new { Id = 100072, Nombre = "AUDITORÍA Y CONTROL DE GESTIÓN", Siglas = "ACG", FacultadId = 1010, Activo = true },
        new { Id = 100073, Nombre = "MERCADOTECNIA", Siglas = "M", FacultadId = 1010, Activo = true },
        new { Id = 100074, Nombre = "GESTIÓN DEL TALENTO HUMANO", Siglas = "GTH", FacultadId = 1010, Activo = true },
        new { Id = 100075, Nombre = "BIENES RAICES", Siglas = "BR", FacultadId = 1010, Activo = true },
        new { Id = 100076, Nombre = "INGENIERIA AGROPECUARIA", Siglas = "IA", FacultadId = 1011, Activo = true },
        new { Id = 100077, Nombre = "INGENIERIA AGROINDUSTRIAL", Siglas = "IA", FacultadId = 1011, Activo = true },
        new { Id = 100078, Nombre = "CIENCIAS DE LA COMUNICACION MENCION PERIODISMO", Siglas = "CCMP", FacultadId = 1012, Activo = true },
        new { Id = 100079, Nombre = "CIENCIAS DE LA COMUNICACION MENCION PUBLICIDAD Y MERCADOTECNIA", Siglas = "CCMPM", FacultadId = 1012, Activo = true },
        new { Id = 100080, Nombre = "CIENCIAS DE LA COMUNICACION MENCION COMUNICACION ORGANIZACIONAL Y RELACIONES PUBLICAS", Siglas = "CCMCORP", FacultadId = 1012, Activo = true },
        new { Id = 100081, Nombre = "CIENCIAS DE LA COMUNICACION MENCION COMUNICACION ORGANIZACIONAL Y RELACIONES PUBLICA", Siglas = "CCMCORP", FacultadId = 1012, Activo = true },
        new { Id = 100082, Nombre = "EDUCACION PARVULARIA", Siglas = "EP", FacultadId = 1013, Activo = true },
        new { Id = 100083, Nombre = "EDUCACION BASICA", Siglas = "EB", FacultadId = 1013, Activo = true },
        new { Id = 100084, Nombre = "CIENCIAS DE LA EDUCACION MENCION COMPUTACION COMERCIO Y ADMINISTRACION", Siglas = "CEMCCA", FacultadId = 1013, Activo = true },
        new { Id = 100085, Nombre = "036-2019", Siglas = "02", FacultadId = 1013, Activo = true },
        new { Id = 100086, Nombre = "EDUCACION ESPECIAL", Siglas = "EE", FacultadId = 1013, Activo = true },
        new { Id = 100087, Nombre = "CIENCIAS DE LA EDUCACION MENCION PSICOPEDAGOGIA Y TECNICAS DE LA ENSEÑANZA", Siglas = "CEMPTE", FacultadId = 1013, Activo = true },
        new { Id = 100088, Nombre = "CIENCIAS DE LA EDUCACION MENCION FISICO MATEMATICAS", Siglas = "CEMFM", FacultadId = 1013, Activo = true },
        new { Id = 100089, Nombre = "CIENCIAS DE LA EDUCACION MENCION PEDAGOGIA", Siglas = "CEMP", FacultadId = 1013, Activo = true },
        new { Id = 100090, Nombre = "CIENCIAS DE LA EDUCACION MENCION CASTELLANO Y LITERATURA", Siglas = "CEMCL", FacultadId = 1013, Activo = true },
        new { Id = 100091, Nombre = "IDIOMAS MENCION INGLES", Siglas = "IMI", FacultadId = 1013, Activo = true },
        new { Id = 100092, Nombre = "CIENCIAS DE LA EDUCACION MENCION CULTURA ESTETICA", Siglas = "CEMCE", FacultadId = 1013, Activo = true },
        new { Id = 100093, Nombre = "CIENCIAS DE LA EDUCACION MENCION HISTORIA Y GEOGRAFIA", Siglas = "CEMHG", FacultadId = 1013, Activo = true },
        new { Id = 100094, Nombre = "EDUCACION PRIMARIA", Siglas = "EP", FacultadId = 1013, Activo = true },
        new { Id = 100095, Nombre = "ODONTOLOGIA", Siglas = "O", FacultadId = 1014, Activo = true },
        new { Id = 100096, Nombre = "NUTRICION Y DIETETICA", Siglas = "ND", FacultadId = 1014, Activo = true },
        new { Id = 100097, Nombre = "ENFERMERÍA", Siglas = "E", FacultadId = 1014, Activo = true },
        new { Id = 100098, Nombre = "PSICOLOGIA", Siglas = "P", FacultadId = 1014, Activo = true },
        new { Id = 100099, Nombre = "TERAPIA OCUPACIONAL", Siglas = "TO", FacultadId = 1014, Activo = true },
        new { Id = 100100, Nombre = "MEDICINA", Siglas = "M", FacultadId = 1014, Activo = true },
        new { Id = 100101, Nombre = "LABORATORIO CLINICO", Siglas = "LC", FacultadId = 1014, Activo = true },
        new { Id = 100102, Nombre = "FONOAUDIOLOGÍA", Siglas = "F", FacultadId = 1014, Activo = true },
        new { Id = 100103, Nombre = "FISIOTERAPIA", Siglas = "F", FacultadId = 1014, Activo = true },
        new { Id = 100104, Nombre = "INGENIERÍA AMBIENTAL", Siglas = "IA", FacultadId = 1015, Activo = true },
        new { Id = 100105, Nombre = "AGROPECUARIA", Siglas = "A", FacultadId = 1015, Activo = true },
        new { Id = 100106, Nombre = "SOFTWARE", Siglas = "S", FacultadId = 1015, Activo = true },
        new { Id = 100107, Nombre = "TECNOLOGÍAS DE LA INFORMACIÓN", Siglas = "TI", FacultadId = 1015, Activo = true },
        new { Id = 100108, Nombre = "AGROINDUSTRIA", Siglas = "A", FacultadId = 1015, Activo = true },
        new { Id = 100109, Nombre = "BIOLOGÍA", Siglas = "B", FacultadId = 1015, Activo = true },
        new { Id = 100110, Nombre = "AGRONEGOCIOS", Siglas = "A", FacultadId = 1015, Activo = true },
        new { Id = 100111, Nombre = "BIOQUIMICA EN ACTIVIDADES PESQUERAS", Siglas = "BAP", FacultadId = 1016, Activo = true },
        new { Id = 100112, Nombre = "ECONOMIA", Siglas = "E", FacultadId = 1017, Activo = true },
        new { Id = 100113, Nombre = "INGENIERIA EN SISTEMAS", Siglas = "IS", FacultadId = 1018, Activo = true },
        new { Id = 100114, Nombre = "MEDICINA", Siglas = "M", FacultadId = 1019, Activo = true },
        new { Id = 100115, Nombre = "COMUNICACIÓN", Siglas = "C", FacultadId = 1020, Activo = true },
        new { Id = 100116, Nombre = "ECONOMIA", Siglas = "E", FacultadId = 1020, Activo = true },
        new { Id = 100117, Nombre = "DERECHO", Siglas = "D", FacultadId = 1020, Activo = true },
        new { Id = 100118, Nombre = "CIENCIAS DE LA COMUNICACION MENCION PERIODISMO", Siglas = "CCMP", FacultadId = 1020, Activo = true },
        new { Id = 100119, Nombre = "COMUNICACIÓN PARA TELEVISIÓN, RELACIONES PÚBLICAS Y PROTOCOLO", Siglas = "CPTRPP", FacultadId = 1020, Activo = true },
        new { Id = 100120, Nombre = "TRABAJO SOCIAL", Siglas = "TS", FacultadId = 1020, Activo = true },
        new { Id = 100121, Nombre = "CIENCIAS POLÍTICAS Y RELACIONES INTERNACIONALES", Siglas = "CPRI", FacultadId = 1020, Activo = true },
        new { Id = 100122, Nombre = "GESTIÓN PÚBLICA Y DESARROLLO", Siglas = "GPD", FacultadId = 1020, Activo = true },
        new { Id = 100123, Nombre = "CRIMINOLOGÍA Y CIENCIAS FORENSES", Siglas = "CCF", FacultadId = 1020, Activo = true },
        new { Id = 100124, Nombre = "COMERCIO EXTERIOR Y NEGOCIOS INTERNACIONALES", Siglas = "CENI", FacultadId = 1021, Activo = true },
        new { Id = 100125, Nombre = "CONTABILIDAD Y AUDITORIA", Siglas = "CA", FacultadId = 1022, Activo = true },
        new { Id = 100126, Nombre = "DERECHO", Siglas = "D", FacultadId = 1023, Activo = true },
        new { Id = 100127, Nombre = "EDUCACION FISICA DEPORTES Y RECREACION", Siglas = "EFDR", FacultadId = 1024, Activo = true },
        new { Id = 100128, Nombre = "EDUCACION FISICA DEPORTES Y RECREACION MENCION ENTRENAMIENTO DEPORTIVO", Siglas = "EFDRMED", FacultadId = 1024, Activo = true },
        new { Id = 100129, Nombre = "EDUCACION BASICA", Siglas = "EB", FacultadId = 1025, Activo = true },
        new { Id = 100130, Nombre = "EDUCACION INICIAL", Siglas = "EI", FacultadId = 1025, Activo = true },
        new { Id = 100131, Nombre = "PEDAGOGÍA DE LA ACTIVIDAD FISICA Y DEPORTE", Siglas = "PAFD", FacultadId = 1025, Activo = true },
        new { Id = 100132, Nombre = "GASTRONOMIA", Siglas = "G", FacultadId = 1025, Activo = true },
        new { Id = 100133, Nombre = "TURISMO SOSTENIBLE", Siglas = "TS", FacultadId = 1025, Activo = true },
        new { Id = 100134, Nombre = "ENTRENAMIENTO DEPORTIVO", Siglas = "ED", FacultadId = 1025, Activo = true },
        new { Id = 100135, Nombre = "EDUCACION BASICA BILINGÜE", Siglas = "EBB", FacultadId = 1025, Activo = true },
        new { Id = 100136, Nombre = "PEDAGOGÍA DE LOS IDIOMAS NACIONALES Y EXTRANJEROS", Siglas = "PINE", FacultadId = 1025, Activo = true },
        new { Id = 100137, Nombre = "HOSPITALIDAD Y HOTELERIA", Siglas = "HH", FacultadId = 1025, Activo = true },
        new { Id = 100138, Nombre = "PEDAGOGÍA DE LA LENGUA Y LA LITERATURA", Siglas = "PLL", FacultadId = 1025, Activo = true },
        new { Id = 100139, Nombre = "PSICOLOGÍA EDUCATIVA", Siglas = "PE", FacultadId = 1025, Activo = true },
        new { Id = 100140, Nombre = "GESTION HOTELERA INTERNACIONAL", Siglas = "GHI", FacultadId = 1025, Activo = true },
        new { Id = 100141, Nombre = "EDUCACION ESPECIAL", Siglas = "EE", FacultadId = 1025, Activo = true },
        new { Id = 100142, Nombre = "EDUCACIÓN INICIAL BILINGÜE", Siglas = "EIB", FacultadId = 1025, Activo = true },
        new { Id = 100143, Nombre = "TURISMO", Siglas = "T", FacultadId = 1025, Activo = true },
        new { Id = 100144, Nombre = "EDUCACIÓN INCLUSIVA", Siglas = "EI", FacultadId = 1025, Activo = true },
        new { Id = 100145, Nombre = "EDUCACION INICIAL", Siglas = "EI", FacultadId = 1026, Activo = true },
        new { Id = 100146, Nombre = "ELECTROMECÁNICA", Siglas = "E", FacultadId = 1026, Activo = true },
        new { Id = 100147, Nombre = "TECNOLOGÍAS DE LA INFORMACIÓN", Siglas = "TI", FacultadId = 1026, Activo = true },
        new { Id = 100148, Nombre = "ALIMENTOS", Siglas = "A", FacultadId = 1026, Activo = true },
        new { Id = 100149, Nombre = "AUDITORÍA Y CONTROL DE GESTIÓN", Siglas = "ACG", FacultadId = 1026, Activo = true },
        new { Id = 100150, Nombre = "SOFTWARE", Siglas = "S", FacultadId = 1026, Activo = true },
        new { Id = 100151, Nombre = "DERECHO", Siglas = "D", FacultadId = 1026, Activo = true },
        new { Id = 100152, Nombre = "AGRONEGOCIOS", Siglas = "A", FacultadId = 1026, Activo = true },
        new { Id = 100153, Nombre = "ENFERMERÍA", Siglas = "E", FacultadId = 1026, Activo = true },
        new { Id = 100154, Nombre = "ADMINISTRACIÓN DE EMPRESAS", Siglas = "AE", FacultadId = 1026, Activo = true },
        new { Id = 100155, Nombre = "FINANZAS", Siglas = "F", FacultadId = 1026, Activo = true },
        new { Id = 100156, Nombre = "AGROPECUARIA", Siglas = "A", FacultadId = 1026, Activo = true },
        new { Id = 100157, Nombre = "INGENIERIA AGROPECUARIA", Siglas = "IA", FacultadId = 1026, Activo = true },
        new { Id = 100158, Nombre = "CONTABILIDAD Y AUDITORIA", Siglas = "CA", FacultadId = 1026, Activo = true },
        new { Id = 100159, Nombre = "INGENIERIA EN SISTEMAS", Siglas = "IS", FacultadId = 1026, Activo = true },
        new { Id = 100160, Nombre = "EDUCACION PRIMARIA", Siglas = "EP", FacultadId = 1026, Activo = true },
        new { Id = 100161, Nombre = "EDUCACION BASICA", Siglas = "EB", FacultadId = 1026, Activo = true },
        new { Id = 100162, Nombre = "PSICOLOGÍA EDUCATIVA", Siglas = "PE", FacultadId = 1026, Activo = true },
        new { Id = 100163, Nombre = "FISIOTERAPIA", Siglas = "F", FacultadId = 1026, Activo = true },
        new { Id = 100164, Nombre = "ELECTROMECÁNICA Y ENERGÍAS RENOVABLES", Siglas = "EER", FacultadId = 1026, Activo = true },
        new { Id = 100165, Nombre = "SECRETARIADO EJECUTIVO", Siglas = "SE", FacultadId = 1027, Activo = true },
        new { Id = 100166, Nombre = "SERVICIOS GERENCIALES", Siglas = "SG", FacultadId = 1027, Activo = true },
        new { Id = 100167, Nombre = "TURISMO", Siglas = "T", FacultadId = 1028, Activo = true },
        new { Id = 100168, Nombre = "HOTELERIA", Siglas = "H", FacultadId = 1028, Activo = true },
        new { Id = 100169, Nombre = "INGENIERIA ELECTRICA", Siglas = "IE", FacultadId = 1029, Activo = true },
        new { Id = 100170, Nombre = "INGENIERIA CIVIL", Siglas = "IC", FacultadId = 1029, Activo = true },
        new { Id = 100171, Nombre = "TECNOLOGIA EN CONSTRUCCION CIVIL", Siglas = "TCC", FacultadId = 1029, Activo = true },
        new { Id = 100172, Nombre = "INGENIERIA INDUSTRIAL", Siglas = "II", FacultadId = 1030, Activo = true },
        new { Id = 100173, Nombre = "INGENIERIA EN ALIMENTOS", Siglas = "IA", FacultadId = 1030, Activo = true },
        new { Id = 100174, Nombre = "INGENIERIA CIVIL", Siglas = "IC", FacultadId = 1031, Activo = true },
        new { Id = 100175, Nombre = "INGENIERÍA MARÍTIMA", Siglas = "IM", FacultadId = 1031, Activo = true },
        new { Id = 100176, Nombre = "ARQUITECTURA", Siglas = "A", FacultadId = 1031, Activo = true },
        new { Id = 100177, Nombre = "INGENIERÍA INDUSTRIAL", Siglas = "II", FacultadId = 1031, Activo = true },
        new { Id = 100178, Nombre = "ALIMENTOS", Siglas = "A", FacultadId = 1031, Activo = true },
        new { Id = 100179, Nombre = "ELECTRICIDAD", Siglas = "E", FacultadId = 1031, Activo = true },
        new { Id = 100180, Nombre = "CONSTRUCCION SISMORRESISTENTE", Siglas = "CS", FacultadId = 1031, Activo = true },
        new { Id = 100181, Nombre = "METALMECÁNICA", Siglas = "M", FacultadId = 1031, Activo = true },
        new { Id = 100182, Nombre = "CORSO DI ITALIANO", Siglas = "CDI", FacultadId = 1032, Activo = true },
        new { Id = 100183, Nombre = "SEMINARIOS DE INGLES", Siglas = "SI", FacultadId = 1032, Activo = true },
        new { Id = 100184, Nombre = "SELF PACED", Siglas = "SP", FacultadId = 1032, Activo = true },
        new { Id = 100185, Nombre = "UEES", Siglas = "U", FacultadId = 1032, Activo = true },
        new { Id = 100186, Nombre = "ENGLISH PROFICIENCY", Siglas = "EP", FacultadId = 1032, Activo = true },
        new { Id = 100187, Nombre = "N/D", Siglas = "ND", FacultadId = 1032, Activo = true },
        new { Id = 100188, Nombre = "SUFFISANCE DE FRANCAIS", Siglas = "SF", FacultadId = 1032, Activo = true },
        new { Id = 100189, Nombre = "CONVENIO EP", Siglas = "CE", FacultadId = 1032, Activo = true },
        new { Id = 100190, Nombre = "INGENIERIA EN MECANICA NAVAL", Siglas = "IMN", FacultadId = 1033, Activo = true },
        new { Id = 100191, Nombre = "ODONTOLOGIA", Siglas = "O", FacultadId = 1034, Activo = true },
        new { Id = 100192, Nombre = "AGROPECUARIA", Siglas = "A", FacultadId = 1035, Activo = true },
        new { Id = 100193, Nombre = "ARQUITECTURA", Siglas = "A", FacultadId = 1035, Activo = true },
        new { Id = 100194, Nombre = "TURISMO", Siglas = "T", FacultadId = 1035, Activo = true },
        new { Id = 100195, Nombre = "BIOLOGÍA", Siglas = "B", FacultadId = 1035, Activo = true },
        new { Id = 100196, Nombre = "INGENIERIA AGROPECUARIA", Siglas = "IA", FacultadId = 1035, Activo = true },
        new { Id = 100197, Nombre = "ADMINISTRACIÓN DE EMPRESAS", Siglas = "AE", FacultadId = 1035, Activo = true },
        new { Id = 100198, Nombre = "ECONOMIA", Siglas = "E", FacultadId = 1035, Activo = true },
        new { Id = 100199, Nombre = "HOTELERIA Y TURISMO", Siglas = "HT", FacultadId = 1035, Activo = true },
        new { Id = 100200, Nombre = "ADMINISTRACION DE EMPRESAS", Siglas = "AE", FacultadId = 1035, Activo = true },
        new { Id = 100201, Nombre = "GASTRONOMIA", Siglas = "G", FacultadId = 1035, Activo = true },
        new { Id = 100202, Nombre = "FISIOTERAPIA", Siglas = "F", FacultadId = 1035, Activo = true },
        new { Id = 100203, Nombre = "ENFERMERÍA", Siglas = "E", FacultadId = 1035, Activo = true },
        new { Id = 100204, Nombre = "EDUCACION INICIAL", Siglas = "EI", FacultadId = 1035, Activo = true },
        new { Id = 100205, Nombre = "DERECHO", Siglas = "D", FacultadId = 1035, Activo = true },
        new { Id = 100206, Nombre = "EDUCACION BASICA", Siglas = "EB", FacultadId = 1035, Activo = true },
        new { Id = 100207, Nombre = "ELECTROMECÁNICA", Siglas = "E", FacultadId = 1035, Activo = true },
        new { Id = 100208, Nombre = "AGRONEGOCIOS", Siglas = "A", FacultadId = 1035, Activo = true },
        new { Id = 100209, Nombre = "ELECTROMECÁNICA Y ENERGÍAS RENOVABLES", Siglas = "EER", FacultadId = 1035, Activo = true },
        new { Id = 100210, Nombre = "INGENIERIA AGROPECUARIA ACUICOLA", Siglas = "IAA", FacultadId = 1035, Activo = true },
        new { Id = 100211, Nombre = "PSICOLOGIA", Siglas = "P", FacultadId = 1036, Activo = true },
        new { Id = 100212, Nombre = "EDUCACION BASICA", Siglas = "EB", FacultadId = 1037, Activo = true },
        new { Id = 100213, Nombre = "ADMINISTRACIÓN DE EMPRESAS", Siglas = "AE", FacultadId = 1037, Activo = true },
        new { Id = 100214, Nombre = "DISEÑO TEXTIL E INDUMENTARIA", Siglas = "DTI", FacultadId = 1037, Activo = true },
        new { Id = 100215, Nombre = "TURISMO SOSTENIBLE", Siglas = "TS", FacultadId = 1037, Activo = true },
        new { Id = 100216, Nombre = "INGENIERIA CIVIL", Siglas = "IC", FacultadId = 1037, Activo = true },
        new { Id = 100217, Nombre = "ARQUITECTURA", Siglas = "A", FacultadId = 1037, Activo = true },
        new { Id = 100218, Nombre = "DERECHO", Siglas = "D", FacultadId = 1037, Activo = true },
        new { Id = 100219, Nombre = "FISIOTERAPIA", Siglas = "F", FacultadId = 1037, Activo = true },
        new { Id = 100220, Nombre = "BIENES RAICES", Siglas = "BR", FacultadId = 1037, Activo = true },
        new { Id = 100221, Nombre = "TRABAJO SOCIAL", Siglas = "TS", FacultadId = 1038, Activo = true },
        new { Id = 100222, Nombre = "PSICOLOGIA", Siglas = "P", FacultadId = 1038, Activo = true },
        new { Id = 100223, Nombre = "TECNOLOGÍA SUPERIOR EN RIEGO Y PRODUCCIÓN AGRÍCOLA", Siglas = "TSRPA", FacultadId = 1039, Activo = true },
        new { Id = 100224, Nombre = "ELECTROMECÁNICA", Siglas = "E", FacultadId = 1039, Activo = true },
        new { Id = 100225, Nombre = "EXPLOTACIÓN Y MANTENIMIENTO DE EQUIPOS BIOMÉDICOS", Siglas = "EMEB", FacultadId = 1039, Activo = true },
        new { Id = 100226, Nombre = "ELECTROMECÁNICA Y ENERGÍAS RENOVABLES", Siglas = "EER", FacultadId = 1039, Activo = true },
        new { Id = 100227, Nombre = "GASTRONOMIA", Siglas = "G", FacultadId = 1039, Activo = true },
        new { Id = 100228, Nombre = "Seminario Curriculares", Siglas = "SC", FacultadId = 1039, Activo = true },
        new { Id = 100229, Nombre = "EDUCACIÓN VIRTUAL", Siglas = "EV", FacultadId = 1039, Activo = true },
        new { Id = 100230, Nombre = "CONSTRUCCION SISMORRESISTENTE", Siglas = "CS", FacultadId = 1039, Activo = true },
    ];
}
