<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DefaultItemExcludes>$(DefaultItemExcludes);src\**;tests\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data\**\*.cs" />
    <Compile Remove="Helpers\**\*.cs" />
    <Compile Remove="Migrations\**\*.cs" />
    <Compile Remove="Models\Models.cs" />
    <Compile Remove="Services\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <ProjectReference Include="src\SistemaConvenios.Application\SistemaConvenios.Application.csproj" />
    <ProjectReference Include="src\SistemaConvenios.Infrastructure\SistemaConvenios.Infrastructure.csproj" />
  </ItemGroup>

</Project>
