// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaConvenios.Data;

#nullable disable

namespace SistemaConvenios.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260625043009_AmpliarLongitudAmbito")]
    partial class AmpliarLongitudAmbito
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UsuarioClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UsuarioLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsuarioRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UsuarioTokens", (string)null);
                });

            modelBuilder.Entity("SistemaConvenios.Models.ActividadConvenio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConvenioId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HorasPlanificadas")
                        .HasColumnType("integer");

                    b.Property<string>("Lugar")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Responsable")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioId");

                    b.ToTable("ActividadesConvenio", (string)null);
                });

            modelBuilder.Entity("SistemaConvenios.Models.AmbitoConvenio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConvenioId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioId", "Nombre")
                        .IsUnique();

                    b.ToTable("AmbitosConvenio", (string)null);
                });

            modelBuilder.Entity("SistemaConvenios.Models.ArchivoConvenio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConvenioId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RutaFisica")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("SubidoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("TamanioBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioId");

                    b.ToTable("ArchivosConvenio", (string)null);
                });

            modelBuilder.Entity("SistemaConvenios.Models.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("FacultadId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Siglas")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("FacultadId");

                    b.ToTable("Carreras", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            FacultadId = 1,
                            Nombre = "Ingeniería de Software",
                            Siglas = "IS"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            FacultadId = 1,
                            Nombre = "Ingeniería Ambiental",
                            Siglas = "IA"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            FacultadId = 1,
                            Nombre = "Medicina Veterinaria",
                            Siglas = "MV"
                        });
                });

            modelBuilder.Entity("SistemaConvenios.Models.CierreConvenio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Causal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ConvenioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ObligacionesPendientes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ResponsablesSeguimiento")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Resumen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioId")
                        .IsUnique();

                    b.ToTable("CierresConvenio", (string)null);
                });

            modelBuilder.Entity("SistemaConvenios.Models.ClausulaConvenio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConvenioId")
                        .HasColumnType("integer");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioId");

                    b.ToTable("ClausulasConvenio", (string)null);
                });

            modelBuilder.Entity("SistemaConvenios.Models.Convenio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ambito")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CondicionesRenovacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("ConfidencialidadIndefinida")
                        .HasColumnType("boolean");

                    b.Property<string>("DomicilioContractual")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("EntidadId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaSuscripcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaUltimaFirma")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FuenteFinanciamiento")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("MecanismoSolucionControversias")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NumeroResolucion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Objeto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("Presupuesto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("RenovacionAutomatica")
                        .HasColumnType("boolean");

                    b.Property<string>("Supervisor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("TieneErogacion")
                        .HasColumnType("boolean");

                    b.Property<int>("TipoConvenioId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioCreadorId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntidadId");

                    b.HasIndex("TipoConvenioId");

                    b.HasIndex("UsuarioCreadorId");

                    b.ToTable("Convenios", (string)null);
                });

            modelBuilder.Entity("SistemaConvenios.Models.ConvenioCarrera", b =>
                {
                    b.Property<int>("ConvenioId")
                        .HasColumnType("integer");

                    b.Property<int>("CarreraId")
                        .HasColumnType("integer");

                    b.HasKey("ConvenioId", "CarreraId");

                    b.HasIndex("CarreraId");

                    b.ToTable("ConvenioCarreras", (string)null);
                });

            modelBuilder.Entity("SistemaConvenios.Models.ConvenioFacultad", b =>
                {
                    b.Property<int>("ConvenioId")
                        .HasColumnType("integer");

                    b.Property<int>("FacultadId")
                        .HasColumnType("integer");

                    b.HasKey("ConvenioId", "FacultadId");

                    b.HasIndex("FacultadId");

                    b.ToTable("ConvenioFacultades", (string)null);
                });

            modelBuilder.Entity("SistemaConvenios.Models.ConvenioRelacionado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConvenioId")
                        .HasColumnType("integer");

                    b.Property<int>("ConvenioRelacionadoId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoRelacion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioRelacionadoId");

                    b.HasIndex("ConvenioId", "ConvenioRelacionadoId")
                        .IsUnique();

                    b.ToTable("ConveniosRelacionados", (string)null);
                });

            modelBuilder.Entity("SistemaConvenios.Models.Entidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CargoRepresentante")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CedulaRepresentante")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RepresentanteLegal")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Ruc")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoEntidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Entidades", (string)null);
                });

            modelBuilder.Entity("SistemaConvenios.Models.EstudianteConvenio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarreraId")
                        .HasColumnType("integer");

                    b.Property<int>("ConvenioId")
                        .HasColumnType("integer");

                    b.Property<bool>("CubiertoSeguro")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NumeroPoliza")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("ConvenioId", "Identificacion")
                        .IsUnique();

                    b.ToTable("EstudiantesConvenio", (string)null);
                });

            modelBuilder.Entity("SistemaConvenios.Models.EvaluacionConvenio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Calificacion")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Conclusion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConvenioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Responsable")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioId");

                    b.ToTable("EvaluacionesConvenio", (string)null);
                });

            modelBuilder.Entity("SistemaConvenios.Models.Facultad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Siglas")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Facultades", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Facultad de Ciencias de la Vida y Tecnologías",
                            Siglas = "FCVT"
                        });
                });

            modelBuilder.Entity("SistemaConvenios.Models.FirmanteConvenio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("ConvenioId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaFirma")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FundamentoRepresentacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Identificacion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ParteConvenioId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoFirma")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioId");

                    b.HasIndex("ParteConvenioId");

                    b.ToTable("FirmantesConvenio", (string)null);
                });

            modelBuilder.Entity("SistemaConvenios.Models.HistorialEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CambiadoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ConvenioId")
                        .HasColumnType("integer");

                    b.Property<string>("EstadoAnterior")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioId");

                    b.ToTable("HistorialEstados", (string)null);
                });

            modelBuilder.Entity("SistemaConvenios.Models.ModificacionConvenio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConvenioId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioId");

                    b.ToTable("ModificacionesConvenio", (string)null);
                });

            modelBuilder.Entity("SistemaConvenios.Models.ObligacionConvenio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ConvenioId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Evidencia")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("FechaCumplimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioId");

                    b.ToTable("ObligacionesConvenio", (string)null);
                });

            modelBuilder.Entity("SistemaConvenios.Models.ParteConvenio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ConvenioId")
                        .HasColumnType("integer");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("EntidadId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean");

                    b.Property<string>("Ruc")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TipoParte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioId");

                    b.HasIndex("EntidadId");

                    b.ToTable("PartesConvenio", (string)null);
                });

            modelBuilder.Entity("SistemaConvenios.Models.ParticipacionActividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActividadConvenioId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Calificacion")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("CertificadoEmitido")
                        .HasColumnType("boolean");

                    b.Property<int>("EstudianteConvenioId")
                        .HasColumnType("integer");

                    b.Property<string>("Evaluacion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("FechaCertificado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HorasAsignadas")
                        .HasColumnType("integer");

                    b.Property<int>("HorasCumplidas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteConvenioId");

                    b.HasIndex("ActividadConvenioId", "EstudianteConvenioId")
                        .IsUnique();

                    b.ToTable("ParticipacionesActividad", (string)null);
                });

            modelBuilder.Entity("SistemaConvenios.Models.ResponsableConvenio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("ConvenioId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ParteConvenioId")
                        .HasColumnType("integer");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioId");

                    b.HasIndex("ParteConvenioId");

                    b.ToTable("ResponsablesConvenio", (string)null);
                });

            modelBuilder.Entity("SistemaConvenios.Models.TipoConvenio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("TiposConvenio", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Convenio marco general",
                            Nombre = "Marco"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Convenio para actividades específicas",
                            Nombre = "Específico"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Convenio con instituciones extranjeras",
                            Nombre = "Internacional"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Otros tipos de convenio",
                            Nombre = "Otro"
                        });
                });

            modelBuilder.Entity("SistemaConvenios.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cargo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SistemaConvenios.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SistemaConvenios.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaConvenios.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SistemaConvenios.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaConvenios.Models.ActividadConvenio", b =>
                {
                    b.HasOne("SistemaConvenios.Models.Convenio", "Convenio")
                        .WithMany("Actividades")
                        .HasForeignKey("ConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convenio");
                });

            modelBuilder.Entity("SistemaConvenios.Models.AmbitoConvenio", b =>
                {
                    b.HasOne("SistemaConvenios.Models.Convenio", "Convenio")
                        .WithMany("Ambitos")
                        .HasForeignKey("ConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convenio");
                });

            modelBuilder.Entity("SistemaConvenios.Models.ArchivoConvenio", b =>
                {
                    b.HasOne("SistemaConvenios.Models.Convenio", "Convenio")
                        .WithMany("Archivos")
                        .HasForeignKey("ConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convenio");
                });

            modelBuilder.Entity("SistemaConvenios.Models.Carrera", b =>
                {
                    b.HasOne("SistemaConvenios.Models.Facultad", "Facultad")
                        .WithMany("Carreras")
                        .HasForeignKey("FacultadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facultad");
                });

            modelBuilder.Entity("SistemaConvenios.Models.CierreConvenio", b =>
                {
                    b.HasOne("SistemaConvenios.Models.Convenio", "Convenio")
                        .WithOne("Cierre")
                        .HasForeignKey("SistemaConvenios.Models.CierreConvenio", "ConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convenio");
                });

            modelBuilder.Entity("SistemaConvenios.Models.ClausulaConvenio", b =>
                {
                    b.HasOne("SistemaConvenios.Models.Convenio", "Convenio")
                        .WithMany("Clausulas")
                        .HasForeignKey("ConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convenio");
                });

            modelBuilder.Entity("SistemaConvenios.Models.Convenio", b =>
                {
                    b.HasOne("SistemaConvenios.Models.Entidad", "Entidad")
                        .WithMany("Convenios")
                        .HasForeignKey("EntidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaConvenios.Models.TipoConvenio", "TipoConvenio")
                        .WithMany("Convenios")
                        .HasForeignKey("TipoConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaConvenios.Models.Usuario", null)
                        .WithMany("ConveniosAdministrados")
                        .HasForeignKey("UsuarioCreadorId");

                    b.Navigation("Entidad");

                    b.Navigation("TipoConvenio");
                });

            modelBuilder.Entity("SistemaConvenios.Models.ConvenioCarrera", b =>
                {
                    b.HasOne("SistemaConvenios.Models.Carrera", "Carrera")
                        .WithMany("ConvenioCarreras")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaConvenios.Models.Convenio", "Convenio")
                        .WithMany("ConvenioCarreras")
                        .HasForeignKey("ConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Convenio");
                });

            modelBuilder.Entity("SistemaConvenios.Models.ConvenioFacultad", b =>
                {
                    b.HasOne("SistemaConvenios.Models.Convenio", "Convenio")
                        .WithMany("ConvenioFacultades")
                        .HasForeignKey("ConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaConvenios.Models.Facultad", "Facultad")
                        .WithMany("ConvenioFacultades")
                        .HasForeignKey("FacultadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convenio");

                    b.Navigation("Facultad");
                });

            modelBuilder.Entity("SistemaConvenios.Models.ConvenioRelacionado", b =>
                {
                    b.HasOne("SistemaConvenios.Models.Convenio", "Convenio")
                        .WithMany("ConveniosRelacionados")
                        .HasForeignKey("ConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaConvenios.Models.Convenio", "Relacionado")
                        .WithMany()
                        .HasForeignKey("ConvenioRelacionadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Convenio");

                    b.Navigation("Relacionado");
                });

            modelBuilder.Entity("SistemaConvenios.Models.EstudianteConvenio", b =>
                {
                    b.HasOne("SistemaConvenios.Models.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaConvenios.Models.Convenio", "Convenio")
                        .WithMany("Estudiantes")
                        .HasForeignKey("ConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Convenio");
                });

            modelBuilder.Entity("SistemaConvenios.Models.EvaluacionConvenio", b =>
                {
                    b.HasOne("SistemaConvenios.Models.Convenio", "Convenio")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("ConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convenio");
                });

            modelBuilder.Entity("SistemaConvenios.Models.FirmanteConvenio", b =>
                {
                    b.HasOne("SistemaConvenios.Models.Convenio", "Convenio")
                        .WithMany("Firmantes")
                        .HasForeignKey("ConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaConvenios.Models.ParteConvenio", "ParteConvenio")
                        .WithMany("Firmantes")
                        .HasForeignKey("ParteConvenioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Convenio");

                    b.Navigation("ParteConvenio");
                });

            modelBuilder.Entity("SistemaConvenios.Models.HistorialEstado", b =>
                {
                    b.HasOne("SistemaConvenios.Models.Convenio", "Convenio")
                        .WithMany("Historial")
                        .HasForeignKey("ConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convenio");
                });

            modelBuilder.Entity("SistemaConvenios.Models.ModificacionConvenio", b =>
                {
                    b.HasOne("SistemaConvenios.Models.Convenio", "Convenio")
                        .WithMany("Modificaciones")
                        .HasForeignKey("ConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convenio");
                });

            modelBuilder.Entity("SistemaConvenios.Models.ObligacionConvenio", b =>
                {
                    b.HasOne("SistemaConvenios.Models.Convenio", "Convenio")
                        .WithMany("Obligaciones")
                        .HasForeignKey("ConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convenio");
                });

            modelBuilder.Entity("SistemaConvenios.Models.ParteConvenio", b =>
                {
                    b.HasOne("SistemaConvenios.Models.Convenio", "Convenio")
                        .WithMany("Partes")
                        .HasForeignKey("ConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaConvenios.Models.Entidad", "Entidad")
                        .WithMany()
                        .HasForeignKey("EntidadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Convenio");

                    b.Navigation("Entidad");
                });

            modelBuilder.Entity("SistemaConvenios.Models.ParticipacionActividad", b =>
                {
                    b.HasOne("SistemaConvenios.Models.ActividadConvenio", "ActividadConvenio")
                        .WithMany("Participantes")
                        .HasForeignKey("ActividadConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaConvenios.Models.EstudianteConvenio", "EstudianteConvenio")
                        .WithMany("Participaciones")
                        .HasForeignKey("EstudianteConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActividadConvenio");

                    b.Navigation("EstudianteConvenio");
                });

            modelBuilder.Entity("SistemaConvenios.Models.ResponsableConvenio", b =>
                {
                    b.HasOne("SistemaConvenios.Models.Convenio", "Convenio")
                        .WithMany("Responsables")
                        .HasForeignKey("ConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaConvenios.Models.ParteConvenio", "ParteConvenio")
                        .WithMany("Responsables")
                        .HasForeignKey("ParteConvenioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Convenio");

                    b.Navigation("ParteConvenio");
                });

            modelBuilder.Entity("SistemaConvenios.Models.ActividadConvenio", b =>
                {
                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("SistemaConvenios.Models.Carrera", b =>
                {
                    b.Navigation("ConvenioCarreras");
                });

            modelBuilder.Entity("SistemaConvenios.Models.Convenio", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("Ambitos");

                    b.Navigation("Archivos");

                    b.Navigation("Cierre");

                    b.Navigation("Clausulas");

                    b.Navigation("ConvenioCarreras");

                    b.Navigation("ConvenioFacultades");

                    b.Navigation("ConveniosRelacionados");

                    b.Navigation("Estudiantes");

                    b.Navigation("Evaluaciones");

                    b.Navigation("Firmantes");

                    b.Navigation("Historial");

                    b.Navigation("Modificaciones");

                    b.Navigation("Obligaciones");

                    b.Navigation("Partes");

                    b.Navigation("Responsables");
                });

            modelBuilder.Entity("SistemaConvenios.Models.Entidad", b =>
                {
                    b.Navigation("Convenios");
                });

            modelBuilder.Entity("SistemaConvenios.Models.EstudianteConvenio", b =>
                {
                    b.Navigation("Participaciones");
                });

            modelBuilder.Entity("SistemaConvenios.Models.Facultad", b =>
                {
                    b.Navigation("Carreras");

                    b.Navigation("ConvenioFacultades");
                });

            modelBuilder.Entity("SistemaConvenios.Models.ParteConvenio", b =>
                {
                    b.Navigation("Firmantes");

                    b.Navigation("Responsables");
                });

            modelBuilder.Entity("SistemaConvenios.Models.TipoConvenio", b =>
                {
                    b.Navigation("Convenios");
                });

            modelBuilder.Entity("SistemaConvenios.Models.Usuario", b =>
                {
                    b.Navigation("ConveniosAdministrados");
                });
#pragma warning restore 612, 618
        }
    }
}
